### ISSUE TITLE
getUnique should not use atomicModifyIORef

### ISSUE THREAD

**Issue by treeowl** [obsidiansystems/prim-uniq#1]
`atomicModifyIORef` is overly lazy. If the uniques aren't inspected promptly, this can leak. The smallest fix is

```haskell
getUniq = unsafePrimToPrim (atomicModifyIORef' nextUniq (\u -> (u + 1, Uniq u)))
```

`atomicModifyIORef'` takes care of the forcing you were trying to do by hand, and more importantly forces the actual function result "from the outside" to limit the leak.

I am rather curious whether there's an even better way, at least for 64-bit systems. The fact that uniques are not guaranteed to be consecutive seems to suggest that there may be a decent way to do it using a two-word counter where the high word may be incremented an arbitrary (but typically small) number of times each time the low word overflows. Such an approach, if feasible, would reduce memory allocation while maintaining over 96 bits of effective uniqueness.

**Comment by int-e** [comment]
@treeowl: Good point, the current attempt at forcing the counter is clearly futile.

**Comment by int-e** [comment]
@treeowl: Is the performance optimization worth tackling? Feel free to reopen this if you think so.

**Comment by treeowl** [comment]
> @treeowl: Is the performance optimization worth tackling? Feel free to reopen this if you think so.

Oh, I have no idea. It was just a thought.

**Comment by treeowl** [comment]
Hmmm. Couldn't we just use `atomic-primops` and use the `Int`-specific atomic operations? That would seem both simple and efficient.
